<a href="https://colab.research.google.com/github/yashraj-02-techie/mldls/blob/main/classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('fetal_health.csv', usecols=['accelerations','fetal_movement','uterine_contractions','light_decelerations','fetal_health'])
print(dataset)

      accelerations  fetal_movement  uterine_contractions  \
0             0.000           0.000                 0.000   
1             0.006           0.000                 0.006   
2             0.003           0.000                 0.008   
3             0.003           0.000                 0.008   
4             0.007           0.000                 0.008   
...             ...             ...                   ...   
2121          0.000           0.000                 0.007   
2122          0.001           0.000                 0.007   
2123          0.001           0.000                 0.007   
2124          0.001           0.000                 0.006   
2125          0.002           0.002                 0.008   

      light_decelerations  fetal_health  
0                   0.000           2.0  
1                   0.003           1.0  
2                   0.003           1.0  
3                   0.003           1.0  
4                   0.000           1.0  
...            

In [ ]:
X =  dataset.iloc[:,0:4].values
Y = dataset.iloc[:,-1].values

In [ ]:
print(X.shape, Y.shape)

(2126, 4) (2126,)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size= 0.2)
print(X_train.shape, X_test.shape)

(1700, 4) (426, 4)


In [ ]:
# Implementing Logistic Regression (which oddly isnt regression)

from sklearn.linear_model import LogisticRegression

logiReg = LogisticRegression()
logiReg.fit(X_train,Y_train)

Y_pred = logiReg.predict(X_test)
print(Y_test, Y_pred)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 3.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 2. 1. 3. 1. 3. 1. 1. 2. 1. 3. 1. 2.
 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 3. 2. 3. 1. 3. 1. 3. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 2. 2. 1. 3. 1. 2. 1. 1. 1. 1. 3. 1. 1. 1. 2. 1. 2. 1.
 1. 2. 1. 1. 1. 2. 1. 2. 1. 3. 3. 1. 3. 1. 1. 1. 1. 1. 3. 1. 2. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1.
 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 3. 1. 1. 2. 1.
 2. 1. 1. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 3. 1. 1.

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

print("Confusion matrix: \n", confusion_matrix(Y_test, Y_pred))
print("Accuracy: \n", accuracy_score(Y_test, Y_pred))
print("Precision: \n", precision_score(Y_test, Y_pred, average=None, zero_division=1))
print("Recall: \n", recall_score(Y_test, Y_pred, average=None, zero_division=1))

Confusion matrix: 
 [[323  16   0]
 [ 57   1   0]
 [ 29   0   0]]
Accuracy: 
 0.7605633802816901
Precision: 
 [0.78973105 0.05882353 1.        ]
Recall: 
 [0.95280236 0.01724138 0.        ]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)

Y_pred_Knn = knn.predict(X_test)
print("Confusion matrix: \n", confusion_matrix(Y_test, Y_pred_Knn))
print("Accuracy: \n", accuracy_score(Y_test, Y_pred_Knn))


Confusion matrix: 
 [[314  20   5]
 [ 40  18   0]
 [ 17   4   8]]
Accuracy: 
 0.7981220657276995


In [ ]:
# Implementing Decision Tree

from sklearn.tree import DecisionTreeClassifier

dTree = DecisionTreeClassifier()
dTree.fit(X_train, Y_train)

Y_pred_dTree = dTree.predict(X_test)

print("Confusion matrix: \n", confusion_matrix(Y_test, Y_pred_dTree))
print("Accuracy: \n", accuracy_score(Y_test, Y_pred_dTree))


Confusion matrix: 
 [[316  17   4]
 [ 17  36   2]
 [  6   6  22]]
Accuracy: 
 0.8779342723004695


In [ ]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

rF = RandomForestClassifier()
rF.fit(X_train, Y_train)

Y_pred_rF = rF.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_rF))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_rF))

Confusion Matrix:
 [[309  16  14]
 [ 27  19  12]
 [  7   5  17]]
Accuracy:
 0.8098591549295775
